### ISSUE TITLE
error on making sensor? Prognose-sensor is there, the other two are not?

### ISSUE THREAD

**Issue by nielswest65** [nelbs/Mindergas-for-Home-Assistant#8]

**Comment by nielswest65** [comment]
I am not a coder :-) I live by UI's and a nobe in HA/ and home automation in general. (also dutch native speaker)

this is the error in the HA logbook.

Logger: homeassistant.components.sensor
Source: custom_components/mindergas/sensor.py:197
Integration: Sensor (documentation, issues)
First occurred: 15:44:57 (1 occurrences)
Last logged: 15:44:57

Error while setting up mindergas platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mindergas/sensor.py", line 36, in setup_platform
    add_entities([GasUsed(username, password, name)], True)
  File "/config/custom_components/mindergas/sensor.py", line 135, in __init__
    self.update()
  File "/config/custom_components/mindergas/sensor.py", line 197, in update
    div = data.find_all("div", class_="table_cell")[1]
IndexError: list index out of range
